services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tyba-api
    restart: always
    ports:
      - '${PORT:-3000}:3000'
    depends_on:
      - postgres
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - RESTAURANTS_API_KEY=${RESTAURANTS_API_KEY}
      - RESTAURANTS_API_URL=${RESTAURANTS_API_URL}
      - CITY_API_KEY=${CITY_API_KEY}
      - CITY_API_URL=${CITY_API_URL}
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - tyba-network
    env_file:
      - .env


  postgres:
    image: postgres:13
    container_name: tyba-postgres
    restart: always
    ports:
      - '${DATABASE_PORT:-5432}:5432'
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tyba-network
    env_file:
      - .env

networks:
  tyba-network:

volumes:
  postgres_data:
